Update quality_manual.md
varianter/handbook pull request #113
Opened 2020-12-01 14:29 UTC by linnhelendyrhaug

Endret/lagt til tekst i HMS-håndbok.

2020-12-01 14:30 UTC, adriansberg commented on src/pages/quality_manual.md
> +### Miljøfyrårnansvarlig
```suggestion
### Miljøfyrtårnansvarlig
```

2020-12-01 14:31 UTC, mikaelbr commented on src/pages/quality_manual.md
> +- Opplever du avvik knyttet til psykososiale forhold (er ting kjipt)? Si i fra til din nærmeste leder eller verneombud over en god kopp kaffe på Fredriksons ❤️
```suggestion
- Opplever du avvik knyttet til psykososiale forhold (er ting kjipt)? Si i fra til din nærmeste leder eller verneombud over en god kopp kaffe på Fredrikssons ❤️
```

2020-12-01 14:32 UTC, adriansberg commented on src/pages/quality_manual.md
> +Vi har utarbeidet en [innkjøpsrutine](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/Innkj%C3%B8psrutine.pdf?csf=1&web=1&e=kUBtMb) o
@cbrevik Boten er kanskje ikke oppdatert etter at [dette](https://github.com/varianter/probot-spellchecker/issues/28) ble løst?

2020-12-01 14:32 UTC, adriansberg commented on src/pages/quality_manual.md
> +Miljøfyrtårnansvarlig har ansvar for oppfølging og håndtering av dette.
```suggestion
Miljøfyrtårnansvarlig har ansvar for oppfølging og håndtering av dette. 
```

2020-12-01 14:32 UTC, mikaelbr commented
Tok meg friheten til å oppdatere fra Fredriksons -> Fredrikssons, @linnhelendyrhaug

2020-12-01 14:33 UTC, cbrevik commented on src/pages/quality_manual.md
> +Vi har utarbeidet en [innkjøpsrutine](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/Innkj%C3%B8psrutine.pdf?csf=1&web=1&e=kUBtMb) o
Nei du, det har jeg ikke pushet. Skal se på det i kveld 👍

2020-12-01 14:33 UTC, adriansberg commented on src/pages/quality_manual.md
> +### Miljøfyrårnansvarlig
```suggestion
### Miljøfyrtårnansvarlig
```

2020-12-01 14:34 UTC, adriansberg commented on src/pages/quality_manual.md
> +### Miljøfyrårnansvarlig
Velg den med eller uten en s. 😄

2020-12-01 14:35 UTC, adriansberg commented on src/pages/quality_manual.md
> +Miljøfyrtårnansvarlig har ansvar for oppfølging og håndtering av dette.
Godt spørsmål, rart at den i det hele tatt viser noe når det er likt.

2020-12-01 14:42 UTC, anders-hammervold approved these changes

2020-12-01 17:23 UTC, mikaelbr commented
@linnhelendyrhaug Veldig bra! Tenker det bare er å publisere i vei! Trykk på denne knappen (kan være det står "Create a merge commit", men det er det samme. Trykk den grønne knappen i alle fall):

<img width="831" alt="Screenshot 2020-12-01 at 18 21 35" src="https://user-images.githubusercontent.com/606374/100774267-2d542400-3402-11eb-9fb1-dd31edf15aa2.png">

2020-12-02 07:16 UTC, oddsve requested changes
Et veldig bra stykke arbeid, som jeg vet er krevende. 

Jeg har noen kommentarer jeg ønsker dere ser igjennom og adresserer.

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +Vi setter oss årlige mål om å redusere vår belastning på miljøet, [vi kildesorterer](https://varianttrh.sharepoint.com/:w:/g/ETmw9NtFBdhKtIVvp-smm0MBh9R9eIB5OcZaAsfld3L70A?e=xxF6kq) og fører regnskap
har også lagt inn noen kommentarer der. En annen fordel med ta mest mulig inn hit er at man da også kan får review på aksept på det innholdet

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +- Rømningsveier og brannslokkingsutstyr er godt merket. [Branninnstruks](https://varianttrh.sharepoint.com/:w:/r/Delte%20dokumenter/HMS/BRANNINSTRUKS.docx?d=wcc479dc4c47a4f3a8fe60a05aa1255b2&csf=1&we
kan vi ikke legge inn branninnstruks i håndboka?

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +HMS-arbeidet. I Variant har vi følgende HMS-dokumentasjon tilgjengelig for alle ansatte:
usikker på denne. Insinuerer det at det også finnes noe som ikke er tilgjengelig for alle?

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Arbeidsavtaler](https://varianttrh.sharepoint.com/Delte%20dokumenter/Forms/AllItems.aspx?viewpath=%2FDelte%20dokumenter%2FForms%2FAllItems%2Easpx&newTargetListUrl=%2FDelte%20dokumenter&viewid=3370
ikke relevant for denne pr forsåvidt, men hvorfor linker vi til signerte avtaler?

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
bør legges et annet sted(altså ikke under kartlegging)

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
Dette gjelder da alle de "godkjente" hms og bærekraftsdokumentene

2020-12-02 07:16 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Skade- og sykefravær](https://medium.com/variant-as/tagged/results)
fint for nå, men her tor jeg Anders kan lage en dedikert visning som det heller kan lenkes til .

2020-12-02 08:42 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +- [Skade- og sykefravær](https://medium.com/variant-as/tagged/results)
Ja, enig. Det lå en død link der tidligere, så mulig det finnes? @anders-hammervold

2020-12-02 10:06 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
@oddsve Tenker du i håndboka eller på Docs?

2020-12-02 10:08 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +- [Arbeidsavtaler](https://varianttrh.sharepoint.com/Delte%20dokumenter/Forms/AllItems.aspx?viewpath=%2FDelte%20dokumenter%2FForms%2FAllItems%2Easpx&newTargetListUrl=%2FDelte%20dokumenter&viewid=3370
🤷‍♀️ Den døde linken lå inne fra før, så oppdaterte den bare.

2020-12-02 11:05 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +Verneombud har ansvar for opplæring i rutiner og vernerunde med alle nyansatte. Viktige endringer i HMS-rutiner formidles på Slack (i #viktig), med lenke til det oppdaterte dokumentet i OneDrive.
```suggestion
Verneombud har ansvar for opplæring av ansatte og oppdatering av aktuelle rutiner. Ved nyansettelser skal verneombud ha opplæring og vernerunde. Skjer viktige endringer i HMS-rutiner, er det verneombud og daglig leder som har ansvaret for at alle ansatte er informert. Dette formidles på Slack (i #viktig), med lenke til oppdatert informasjon i håndboka.
```

2020-12-02 11:07 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +Miljøfyrtårnansvarlig velges for to år om gangen. Ansvarlig fra 2020 er Simen Strøm Braaten. [Ansvarsområdet kan leses her](https://varianttrh.sharepoint.com/:w:/g/EV8J0KoqPHxKndxz1qAZpPQBFFd938unI7n
Det har vi ikke tatt stilling til. Om det skal velges av ansatte hadde det kanskje vært fint å gjøre det samtidig som valg av verneombud, slik at rulleringen blir lik? Hva tenker dere, @anders-hammervold @oddsve

2020-12-02 11:09 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +- Rømningsveier og brannslokkingsutstyr er godt merket. [Branninnstruks](https://varianttrh.sharepoint.com/:w:/r/Delte%20dokumenter/HMS/BRANNINSTRUKS.docx?d=wcc479dc4c47a4f3a8fe60a05aa1255b2&csf=1&we
Som eget punkt tenker du? @oddsve

2020-12-02 11:10 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +HMS-arbeidet. I Variant har vi følgende HMS-dokumentasjon tilgjengelig for alle ansatte:
```suggestion
HMS-arbeidet. I Variant har vi følgende HMS-dokumentasjon tilgjengelig:
```

2020-12-02 11:49 UTC, oddsve commented on src/pages/quality_manual.md
> +- Rømningsveier og brannslokkingsutstyr er godt merket. [Branninnstruks](https://varianttrh.sharepoint.com/:w:/r/Delte%20dokumenter/HMS/BRANNINSTRUKS.docx?d=wcc479dc4c47a4f3a8fe60a05aa1255b2&csf=1&we
Som et punkt under HMS-håndboka tenkte jeg

2020-12-02 11:50 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Arbeidsavtaler](https://varianttrh.sharepoint.com/Delte%20dokumenter/Forms/AllItems.aspx?viewpath=%2FDelte%20dokumenter%2FForms%2FAllItems%2Easpx&newTargetListUrl=%2FDelte%20dokumenter&viewid=3370
helt fint nå.Vi må tenke på hvorfor vi gjør akkurat dette.

2020-12-02 11:52 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
Det finnes ting som ikke kan legges åpent med tanke på vern av personlig infor etc og ting som ikke egner seg. Kursoversikt kan gjerne ligge åpent den, årsplanen kanskje ikke? Det det gir mening at info skal ligge på en fil, ønsker jeg meg en folder hvor det er tydelig at her er gjeldene versjon.

2020-12-02 11:53 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Skade- og sykefravær](https://medium.com/variant-as/tagged/results)
Tror ikke den finnes altså. men vi kan høre hvor mye arbeid det er å lage en dedikert visning. på docs. @anders-hammervold ?

2020-12-02 12:51 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
Per nå er det lagt opp slik at de dokumentene vi har laget til sertifiseringen ligger under bærekraft - utfylte dokumenter samt hentet fra HMS-mappa det som allerede var eller ble ferdigutfylt. Men er enig i at det mest hensiktsmessige hadde vært å ha alt samlet på et sted. Tenker at Simen og Ellen kan ta en runde for å strukturere dette på docs? Når det gjelder hva som er åpent, ser jeg ikke hvorfor ikke årsplanen kan ligge åpent for alle oss i Variant?

2020-12-02 13:04 UTC, oddsve commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
Så bare at mange dok lå under Kartlegging 2020. Årsplanen kan ligge åpent for alle varianter ja. Åpen for alle i verden? gjerne det. Usikker om formatet er så egnet til håndboka bare?

2020-12-02 13:12 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +- [Årsplan for HMS-aktiviteter](https://varianttrh.sharepoint.com/:b:/r/Delte%20dokumenter/B%C3%A6rekraft/Utfylte%20dokumenter/Kartlegging%202020/1948%20-%20HMS+aktivitetsplan.pdf?csf=1&web=1&e=qzg4e
Ja, ferdigutfylte dokumenter ligger under kartlegging 2020. Det som er mulig er jo å lenke til all den type dokumentasjon samlet (så lenge den er på samme sted)? Da unngår man å ramse opp alle (hvor flere kanskje av ulike grunner ikke er åpne for alle i verden).

2020-12-15 08:08 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +Miljøfyrtårnansvarlig velges for to år om gangen. Ansvarlig fra 2020 er Simen Strøm Braaten. [Ansvarsområdet kan leses her](https://varianttrh.sharepoint.com/:w:/g/EV8J0KoqPHxKndxz1qAZpPQBFFd938unI7n
@oddsve jeg tenker at det fortsatt kan stå slik i håndboka? Så kan det tas opp i ledergruppa hvilket valg det skal være?

2020-12-15 08:11 UTC, oddsve commented on src/pages/quality_manual.md
> +Miljøfyrtårnansvarlig velges for to år om gangen. Ansvarlig fra 2020 er Simen Strøm Braaten. [Ansvarsområdet kan leses her](https://varianttrh.sharepoint.com/:w:/g/EV8J0KoqPHxKndxz1qAZpPQBFFd938unI7n
```suggestion
Miljøfyrtårnansvarlig engasjeres for to år om gangen. Ansvarlig fra 2020 er Simen Strøm Braaten. [Ansvarsområdet kan leses her](https://varianttrh.sharepoint.com/:w:/g/EV8J0KoqPHxKndxz1qAZpPQBFFd938unI7nvt0Ljf4ySpg?e=Ig4lcO). Kontaktinformasjon finnes på hjemmeside og i våre internsystemer. 
```

2020-12-15 08:12 UTC, oddsve commented on src/pages/quality_manual.md
> +Miljøfyrtårnansvarlig velges for to år om gangen. Ansvarlig fra 2020 er Simen Strøm Braaten. [Ansvarsområdet kan leses her](https://varianttrh.sharepoint.com/:w:/g/EV8J0KoqPHxKndxz1qAZpPQBFFd938unI7n
Forslaget over tar ikke stilling til hvordan ansvarlig velges

2020-12-15 10:33 UTC, linnhelendyrhaug commented on src/pages/quality_manual.md
> +Vi setter oss årlige mål om å redusere vår belastning på miljøet, [vi kildesorterer](https://varianttrh.sharepoint.com/:w:/g/ETmw9NtFBdhKtIVvp-smm0MBh9R9eIB5OcZaAsfld3L70A?e=xxF6kq) og fører regnskap
Kildesorteringsdokumentet er oppdatert.

2020-12-21 11:54 UTC, oddsve approved these changes

2020-12-21 11:57 UTC, merged