WIP V3
varianter/handbook pull request #158
Opened 2022-01-05 10:36 UTC by mikaelbr

2022-03-15 21:09 UTC, mikaelbr commented
Må fikse: optional login. Burde fungere lokalt uten login

2022-03-15 21:57 UTC, AndersNS reviewed
Har bare sett litt overordnet, ikke finlest koden :)

2022-03-15 21:57 UTC, AndersNS commented on .env.example
> +# Get from Azure AD registered App settings.
Bør inn i readme hvor man får tak i disse her lokalt

2022-03-15 21:57 UTC, AndersNS commented on search-index/index.mjs
> +import { dirname, join } from "path";
Ikke typescript for disse filene?

2022-03-15 21:57 UTC, AndersNS commented on pages/api/auth/[...nextauth].ts
> +import AzureADProvider from "next-auth/providers/azure-ad";
Føles litt overkill med login bare for å velge en default lokasjon? Enklere løsning er å bare huske valgt lokasjon i cookie elns, uten å hente det fra AD. Er raskere for meg å bare velge Trondheim enn å logge inn 🤔

2022-03-15 22:01 UTC, mikaelbr commented on pages/api/auth/[...nextauth].ts
> +import AzureADProvider from "next-auth/providers/azure-ad";
Ja, jo, på en måte. Samtidig åpner det mulighetene for å f.eks vise nødvendig hemmelig info wifi-passord om nødvendig (gitt noen flere mekanismer), og mange andre potensielle hjelpefunksjoner etterhvert. Og følte at det er nesten like mye arbeid med cookie som det er med innlogging, bare at innlogging har noe mer muligheter. Men jeg syns det er viktig at vi fortsatt jobber med at det er optional da.

2022-03-16 08:52 UTC, AndersNS commented on pages/api/auth/[...nextauth].ts
> +import AzureADProvider from "next-auth/providers/azure-ad";
Okei. Greit nok svar det ! 

Var bare redd for at det skulle bli tungvindt. Jeg er nok inne såpass sjelden at innloggingen har gått ut mellom hver gang.

2022-03-16 08:53 UTC, AndersNS commented on .env.example
> +# Get from Azure AD registered App settings.
Eventuelt se på sops eller noen av de andre løsningen for secrets som ble postet på slack. :D

2022-03-16 08:58 UTC, mikaelbr commented on .env.example
> +# Get from Azure AD registered App settings.
Ja, kunne egentlig ha tenkt meg å gjøre det slik: https://vercel.com/docs/concepts/projects/environment-variables#development-environment-variables

men så har du utfordringer med prismodellen til vercel........


---

Når det er sagt, så tenker jeg dette er og noe som skal på plass: https://github.com/varianter/handbook/pull/158#issuecomment-1068476187

Og generell dokumentasjon er uansett fint her da.

2022-03-16 10:02 UTC, mikaelbr commented on search-index/index.mjs
> +import { dirname, join } from "path";
Det er direkte node-filer som kalles via node. Bruker foreløpig ikke ts-node for filene må være gjenbrukbar med plugins på tvers av indeksering og konfigurasjon av `next.config.mjs`. Etterhvert for det har stabilisert seg og jeg får løst et par ting som er buggy (rundt dedupe av tre og noder) så blir dette trolig et eget verktøy som kan brukes på tvers av løsninger.

2022-03-16 11:33 UTC, sarahse commented on search-index/index.mjs
> +// const file = join(__dirname, "../pages/test.mdx");
```suggestion
```

Denne skal bort eller?

2022-03-16 11:37 UTC, sarahse commented on src/components/department/index.tsx
> +  showAnon?: boolean;
Det er ikke mulig å skrive ut disse propene? Er det `showAnonymous` det står for? Hva betyr det?

2022-03-16 11:41 UTC, sarahse commented on src/layouts/general/index.tsx
> +  toc,
hva er toc?

2022-03-16 11:47 UTC, sarahse commented on src/search/index.tsx
> +        <Configure hitsPerPage={8} />
burde `hitsPerPage` være en konstant?

2022-03-16 13:08 UTC, sarahse commented on src/layouts/handbook/index.tsx
> +}
Stemmer det at lenkene ved overskriftene er borte nå? Slik ser det ut til meg:
<img width="802" alt="Skjermbilde 2022-03-16 kl  14 07 40" src="https://user-images.githubusercontent.com/6595982/158596709-7412f6dc-0d84-4a1d-a6bd-91569760f13f.png">

Det er altså ingen `#` med mulighet til å lenke til et avsnitt

2022-03-17 17:44 UTC, mikaelbr commented on src/layouts/handbook/index.tsx
> +}
Ja, det burde fikses!

2022-03-17 17:46 UTC, mikaelbr commented on src/components/department/index.tsx
> +  showAnon?: boolean;
Good catch, her bærer det preg av eksperimentering som jeg har glemt at jeg holdt på med når jeg bestemte meg for å gjøre om fra draft. Jeg skal ta en runde på signaturene her generelt!

2022-03-17 17:49 UTC, mikaelbr commented on .prettierrc
> -  "proseWrap": "always"
Endre denne til å bruke felles config fra styleguide.

2022-03-17 17:49 UTC, mikaelbr commented on mdx-plugins/index.mjs
> +  [remarkMdxFrontmatter, { name: "meta" }],
meta burde kanskje bare hete `frontmatter`

2022-03-17 17:50 UTC, mikaelbr commented on next.config.mjs
> +      {
Dette kan sikkert fjernes nå

2022-03-17 17:53 UTC, mikaelbr commented on search-index/indexer.mjs
> +      return [innerNode, output];
Ikke i bruk, burde fjernes. også feil retur signatur.

2022-03-17 17:59 UTC, mikaelbr commented on src/layouts/general/index.tsx
> +const metadata = {
Dette burde genereres og heller hete noe som sitemap eller noe. Men en kombinasjon av fast-glob + frontmatter burde funke, dersom vi dropper automatisk støtte for `[slug].mdx` f.eks. Men det er vel ikke så naturlig her uansett.

2022-03-17 20:56 UTC, mikaelbr commented on src/layouts/general/index.tsx
> +  toc,
Det er en ikke heeelt uvanlig forkortelse av `Table of Contents` 😅 . Delvis valgt av historiske årsaker men også av latskap

2022-03-18 08:54 UTC, sarahse commented on src/layouts/general/index.tsx
> +  toc,
aha! lærer noe nytt hver dag 👍

2022-03-18 14:52 UTC, mikkelbd commented
Det er en feil ved søk på ord med f.eks. æøå nede fra søkeboksen til høyre. Søkte på "tørkeskap", og det gir url som er url-encoded: https://handbook-git-v3-variant1.vercel.app/search?query=t%25C3%25B8rkeskap. Men det blir også brukt/overført direkte til søkefeltet, og det gir 0 resultater. 

Hvis man søker direkte i det store søkefeltet etter "tørkeskap", så fungerer det. 

Ser også ut til å være noe visuelt feil med X i søkefeltet og de antall søkeresultater for Trondheim og Molde på bildene her? Kanskje noe cache eller css som ikke blir loadet korrekt. Har prøvd å slette alle site data/cache, men får det ikke til å se annerledes ut.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/594277/159024967-fb07c41d-7ee1-47d2-ab5f-a62023a0ad14.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/594277/159025378-be5c96d2-963d-4040-a7b2-450810091add.png">

2022-10-16 20:05 UTC, mikaelbr commented
@tormodhau Tenker denne er OK good to go. Alltids noe å gjøre og fikse opp på, men fått oppdatert alle avhengigheter, fikset merge conflicts, fikset litt her og der og løst alle breaking changes.

2022-10-17 08:51 UTC, tormodhau commented on src/components/search-form/search.module.css
> +    0px 2.50747px 2.74791px rgba(0, 0, 0, 0.0155009);
Dette var en veeeeldig presis box-shadow. Hvilket verktøy brukte du for å generere den?

2022-10-17 08:59 UTC, mikaelbr commented on src/components/search-form/search.module.css
> +    0px 2.50747px 2.74791px rgba(0, 0, 0, 0.0155009);
Finnes veldig mange sånne "shadow generators" eller "pretty shadow" som skal gi mer reell skyggedybde. Husker ikke hvilken det var for den der annet enn at jeg har brukt noen forskjellige 😄

2022-10-17 11:13 UTC, tormodhau commented
@mikaelbr Innlogging fungerer ikke for meg på https://handbook-git-v3-variant1.vercel.app/. Er det meningen at det skal fungere i dette miljøet?

![Skjermbilde 2022-10-17 kl  13 10 49](https://user-images.githubusercontent.com/4433808/196163049-cd38e35f-1833-4fd1-a7e2-81c68a1708d0.png)

2022-10-17 12:02 UTC, mikaelbr commented
Hmm. Ja. Det funke' for mæ. Må undersøke

2022-10-17 12:26 UTC, tormodhau commented
> @tormodhau Tenker denne er OK good to go. Alltids noe å gjøre og fikse opp på, men fått oppdatert alle avhengigheter, fikset merge conflicts, fikset litt her og der og løst alle breaking changes. Så gjerne se over litt så kan vi ev. merge.

Jeg synes dette ser veldig bra ut! Foruten at innlogginga ikke fungerer tenker jeg også at denne er klar for merge. 👏 

Noterte et par ting av mindre betydning som kan tas senere. På toppen av ønskelista er en overordnet readme av for hvordan søkeindekseringa er laga, sånn at andre som skal jobbe med den har noen "knagger å henge seg på" (tror jeg fant på det uttrykket akkurat nå!).

Bra jobba! 👏

2022-10-17 12:27 UTC, tormodhau commented
> Hmm. Ja. Det funke' for mæ. Må undersøke

Tipper jeg mangler en rettighet i Azure, kanskje?

2022-10-17 12:28 UTC, mikaelbr commented
Mulig, men det vil være aktuelt for andre og da

2022-10-17 12:30 UTC, adriansberg commented
![image](https://user-images.githubusercontent.com/14045515/196177334-23165d07-5e2d-4bdd-a5e8-498bcf3391d2.png)

2022-10-17 17:09 UTC, mikaelbr commented
@adriansberg @tormodhau Funker det nå?

2022-10-17 17:32 UTC, adriansberg commented
@mikaelbr Får ikke sjekka. Sidemenyen funker ikke på iOS Firefox sæ får ikke logga inn.

2022-10-17 17:39 UTC, mikaelbr commented
Fiksa

2022-10-17 17:40 UTC, adriansberg commented
```
Adrian Santana Berg ({"error":{"code":"Request_BadRequest","message":"Cannot write the value 'null' in raw format.","innerError":{"date":"2022-10-17T17:40:08","request-id":"d5140daf-22ba-40fd-a8eb-1cb5a5ff3f42","client-request-id":"d5140daf-22ba-40fd-a8eb-1cb5a5ff3f42"}}})
```

2022-10-17 17:48 UTC, adriansberg commented
Funker nå!

2022-10-17 17:51 UTC, mikaelbr commented
Det var nok for du manglet department i Azure AD. Ser nesten alle gjør det 😓 Mulig vi enten må bruke bemanning eller oppdatere Azure AD med rett data.

2022-10-17 18:03 UTC, tormodhau commented
Når vi er inne på mobiltesting: 
![B698D0DA-225D-44AE-9DD6-BF66265D37E8](https://user-images.githubusercontent.com/4433808/196249883-95e22e73-b33a-48a4-9cd7-947be280f36e.png)

2022-10-17 18:11 UTC, mikaelbr commented
Fixed

2022-10-17 18:34 UTC, tormodhau commented
Jeg får også til å logge inn nå, men får «(none)» etter navnet. Antar jeg ikke har department i Azure. Samtidig kjenner jeg litt på at dette reviewet må lukkes snart - det er mange endringer! 

Hva tenker dere, @mikaelbr @adriansberg? Skal vi merge og heller rette småfeil som oppdages etterhvert? Om ingen får brukt innlogginga (og vi ikke tenker å gjøre noe med det rett etter merge), så kan kanskje knappen skjules midlertidig?

2022-10-17 18:36 UTC, tormodhau commented
Det er godt mulig at dette er første gang jeg gjør pull requests i Github 😅😅

2022-10-17 19:55 UTC, tormodhau commented
@adriansberg, jeg så gjennom koden tidligere i dag. Det er veldig mye, så noe særlig grundig gjennomgang har jeg ikke gjort. Prøver å finne en knapp for å "Approve", men det er visstnok ikke sånn Github PR funker... eller så er jeg blind. 😄

2022-10-17 19:56 UTC, adriansberg commented
@tormodhau Skal være en grønn knapp øverst på sida, der det står "Add your review". 😄 Jeg kan se over koden nå.

2022-10-17 19:58 UTC, tormodhau approved these changes

2022-10-17 20:09 UTC, adriansberg requested changes

2022-10-17 20:09 UTC, adriansberg commented on pages/api/auth/[...nextauth].ts
> +      // TO ENV
Det er kanskje ikke behov for denne kommentaren?

2022-10-17 20:12 UTC, adriansberg commented
![image](https://user-images.githubusercontent.com/14045515/196273850-27a18fad-fe46-4c96-8ae8-48f62f087381.png)

Lite luft over filtrering når det kun er en avdeling å filtrere på.

2022-10-17 20:18 UTC, adriansberg commented
![image](https://user-images.githubusercontent.com/14045515/196274450-c700ab21-1921-417b-8398-743800bc583b.png)

Riktig avdeling blir ikke satt som aktiv hvis man hopper fra søkeresultat til en seksjon. Må kanskje utvide `isActiveHandbook`.

2022-10-18 08:52 UTC, mikaelbr commented on src/layouts/general/index.tsx
> +
Glad i økosystem jeg altså, men tenker at for utils som er på en linje så trenger vi ikke flere innslag i lockfiles og package files enn vi har i kildekodelinjer 😄

2022-10-18 08:53 UTC, mikaelbr commented on search-index/index.mjs
> +import { dirname, join } from 'path';
Ja, det har stått litt på agendaen uten at jeg har kommet meg rundt til det. Kan se på det i kveld men tenker det trenger ikke å blokkere merge sånn da

2022-10-18 08:57 UTC, mikaelbr commented on next.config.mjs
> +          }
Den løser at det er mulig å ha non-pure selectorer i CSS Modules, som ikke er default for CSS modules config som inkludert av Next.js. Litt escape-hatch men noen ganger påkrevd av bruk av eksterne avhengigheter osv.

2022-10-18 08:57 UTC, mikaelbr commented on pages/information.mdx
> +<DepartmentItem dep="all">
Det kan være markdown også.

2022-10-18 09:42 UTC, tormodhau commented on search-index/index.mjs
> +import { dirname, join } from 'path';
Enig! Ikke en blokker, men greit å få på plass. 5 stikkord eller en paragraf som forklarer at vi søker i AST og sender det til Algolia er bedre enn ingenting. :-)

2022-10-18 10:59 UTC, merged