fix: h3 between h2 and h4
varianter/handbook pull request #273
Opened 2023-04-12 13:40 UTC by TrymVei

2023-04-13 06:43 UTC, TrymVei commented
mulighet til å fjerne enkelte headings fra navbaren, men kan fortsatt bruke h3

2023-04-13 06:46 UTC, mikaelbr commented on src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
> +  if (headingValue === 'Vårt formål er å utvikle samfunnet vi lever i') {
Finnes det mulighet for å f.eks wrappe i en "ignore boks" eller noe? Dette slår meg som veldig sårbart for om noen endrer en tittel

2023-04-13 06:47 UTC, mikaelbr commented on src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
> +  if (headingValue === 'Vårt formål er å utvikle samfunnet vi lever i') {
Altså om det er mulig å sende inn `<h3 className="toc-ignore">` og på andre siden se den klassen

2023-04-13 06:48 UTC, TrymVei commented on src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
> +  if (headingValue === 'Vårt formål er å utvikle samfunnet vi lever i') {
Kan gi det et forsøk

2023-04-24 08:37 UTC, mikaelbr commented on src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
> +  if(toc.attributes.className === "toc-ignore") {
Er `attributes` her egen greie fra TOC-generatoren? Kan kanskje være noe som dette for å støtte flere tilfeller hvor det ikke BARE er toc-ignore som klasse:

```suggestion
  if(toc.attributes.className?.includes("toc-ignore")) {
```

2023-04-24 08:38 UTC, mikaelbr commented on src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
> +  if(toc.attributes.className === "toc-ignore") {
Her kan det og egentlig forenkles til å returnere fremfor if / else med true false. Altså:

```ts
const checkIfHeadingShouldBeRemoved = (toc: TocItem) => {
  return toc.attributes.className?.includes("toc-ignore") ?? false;
}
```

2023-04-24 08:39 UTC, TrymVei commented on src/components/navbarLinks/checkIfHeadingShouldBeRemoved.tsx
> +  if(toc.attributes.className === "toc-ignore") {
Blir generert fra TOC-generatoren ja

2023-04-24 08:42 UTC, mikaelbr requested changes

2023-04-24 08:42 UTC, mikaelbr commented on src/types/toc.d.ts
> +    className: string;
Er denne alltid en streng? Selv om den ikke er satt?

2023-04-24 10:28 UTC, merged