feat: added baerekraft heading for Trondheim and Bergen
varianter/handbook pull request #345
Opened 2024-08-27 11:20 UTC by TrymVei

## Description
@strombraaten wanted to add a bærekraft section under Trondheim and Bergen to add text easier

2024-08-27 11:27 UTC, strombraaten commented
Just to add: We're doing this to make it easier to communicate Variant's sustainability work. It differs from city to city, and although our overarching goals are the same nationwide, we have different goals locally, and different areas of focus.

By adding a sub-section for each city we're making it easier for the people who needs to do the writing to actually.. do the writing.

2024-09-04 11:10 UTC, mikaelbr commented
Mulig bare jeg som ikke er into dette nok til å skjønne det @TrymVei og @strombraaten , men er det virkelig at det mangler en header som gjør at det ikke står noe tekst der? 😅

2024-09-04 14:42 UTC, TrymVei commented
> Mulig bare jeg som ikke er into dette nok til å skjønne det @TrymVei og @strombraaten , men er det virkelig at det mangler en header som gjør at det ikke står noe tekst der? 😅

Tror Simen tenkte det var mer avansert enn å bare lage en heading. Lurer på om vi kan slette denne branchen, eller hva @strombraaten

2024-09-05 07:42 UTC, strombraaten commented
@mikaelbr Hehe, godt spørsmål du. Nei, det er ikke mangelen på en overskrift akkurat, men det er heller det at alle selskapene må komme i gang med å skrive noe der. Og i Oslo har vi allerede starta.

Vi må kommunisere bærekraftsarbeidet som gjøres (krav fra Miljøfyrtårn), og for å få ballen til å rulle spørte jeg @TrymVei om å legge inn en overskrift til hver av byene.

Rett og slett for å legge litt press på de andre bærekraftsfolka (hint hint @carinamnk @jonasbjoralt og @AnitaSteinstad), og for at folk heller skulle irritere seg over at det var en overskrift uten medfølgende tekst. At det provoserer en handling, nettopp fordi det mangler noe. Sammenligna med om plassen ikke er tilrettelagt for det fra før.

Det strider litt mot mine designer-gener, men erfaringsmessig så funker det overraskende bra!

2024-09-05 08:37 UTC, strombraaten commented on pages/avdelinger/bergen.mdx
> +
Legg til denne teksten under headingen

Vi gjør nok mange flere tiltak enn man skulle tro på bærekraftsfronten, som sertifisering gjennom Miljøfyrtårn, fortløpende klimaregnskap, og at hvert av selskapene våres skal streve etter å bli karbonnøytrale for hele sin levetid:
- Som det yngste selskapet i Variant Norge jobber vi i Bergen nå med å etablere rutinene våres.
    - For øyeblikket holder vi på å sertifisere oss som Miljøfyrtårn.

2024-09-05 08:37 UTC, strombraaten commented on pages/avdelinger/trondheim.mdx
> +
Legg til denne teksten under headingen:

> Vi gjør nok mange flere tiltak enn man skulle tro på bærekraftsfronten, som sertifisering gjennom Miljøfyrtårn, fortløpende klimaregnskap, og at hvert av selskapene våres skal streve etter å bli karbonnøytrale for hele sin levetid:
- I Trondheim har vi vært sertifiserte som Miljøfyrtårn siden 2020, kartlagt våre utslipp i et klimaregnskap siden 2021, og innført karbonkompensering i 2022 som et tiltak for å oppnå karbonnøytralitet på sikt.
- Nå jobber vi med å profesjonalisere rutinene våres i større grad, og se på hvordan vi kan utgjøre en større forskjell for kundene våre.

2024-09-05 08:38 UTC, strombraaten requested changes
la til mer beskrivende tekst nå så det ikke bare er tomme overskrifter

2024-10-17 10:26 UTC, strombraaten approved these changes
looks good to me 👌

2024-10-17 10:26 UTC, strombraaten commented
Glemte helt bort den her, @TrymVei, men med mindre det er noe annet vi må vente på så kan den her squashes og merges

2024-10-29 08:58 UTC, jonasbjoralt approved these changes
Teksten for Trondheim er kanskje litt utdatert nå, fordi det er oppe til vurdering om vi fortsatt skal prøve å være karbonnøytrale. Her blir vi klokere etter neste variantdag, men inntil da kan dette stå. Så kan vi heller diskutere om vi skal endre teksten

2024-10-31 19:51 UTC, strombraaten commented
> Teksten for Trondheim er kanskje litt utdatert nå, fordi det er oppe til vurdering om vi fortsatt skal prøve å være karbonnøytrale. Her blir vi klokere etter neste variantdag, men inntil da kan dette stå. Så kan vi heller diskutere om vi skal endre teksten

Supert! Da squasher jeg og merger, @jonasbjoralt 👌

2024-10-31 19:51 UTC, merged